# Generated by Django 5.2.11 on 2026-02-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название лицензии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('commercial_use_allowed', models.BooleanField(default=False, verbose_name='Коммерческое использование')),
                ('resale_allowed', models.BooleanField(default=False, verbose_name='Перепродажа')),
                ('modification_allowed', models.BooleanField(default=True, verbose_name='Изменение')),
                ('attribution_required', models.BooleanField(default=False, verbose_name='Требуется указание автора')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('model_format', models.CharField(choices=[('glb', 'GLB'), ('gltf', 'GLTF'), ('obj', 'OBJ'), ('fbx', 'FBX'), ('blend', 'BLEND'), ('other', 'Other')], default='glb', max_length=20, verbose_name='Формат')),
                ('geometry_type', models.CharField(choices=[('polygonal', 'Polygonal'), ('procedural', 'Procedural'), ('other', 'Other')], default='polygonal', max_length=20, verbose_name='Геометрия')),
                ('topology_type', models.CharField(choices=[('quad', 'Quad'), ('triangulated', 'Triangulated'), ('mixed', 'Mixed'), ('other', 'Other')], default='quad', max_length=20, verbose_name='Топология')),
                ('polygon_count', models.PositiveIntegerField(default=0, verbose_name='Количество полигонов')),
                ('has_uv', models.BooleanField(default=False, verbose_name='Есть UV')),
                ('has_textures', models.BooleanField(default=False, verbose_name='Есть текстуры')),
                ('texture_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип текстур')),
                ('has_rigging', models.BooleanField(default=False, verbose_name='Есть риг')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Статус')),
                ('main_preview', models.ImageField(blank=True, null=True, upload_to='products/previews/', verbose_name='Главное превью')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='Количество избранного')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Количество продаж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Категория')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.license', verbose_name='Лицензия')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('model', '3D Model'), ('texture', 'Texture'), ('preview', 'Preview'), ('uv_preview', 'UV Preview'), ('wireframe_preview', 'Wireframe Preview'), ('other', 'Other')], default='model', max_length=30, verbose_name='Тип файла')),
                ('file', models.FileField(upload_to='products/files/', verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исходное имя')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME-тип')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер файла в байтах')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Файл товара',
                'verbose_name_plural': 'Файлы товара',
                'ordering': ['-created_at'],
            },
        ),
    ]
