# Generated by Django 5.2.11 on 2026-02-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_moderation_comment_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poly_style',
            field=models.CharField(blank=True, choices=[('low_poly', 'Low-poly'), ('mid_poly', 'Mid-poly'), ('high_poly', 'High-poly')], max_length=20, null=True, verbose_name='Стиль полигональности'),
        ),
    ]
