# Generated by Django 5.2.11 on 2026-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_preview_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL главного превью'),
        ),
        migrations.AddField(
            model_name='productfile',
            name='storage_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь в Supabase'),
        ),
    ]
