# Generated by Django 5.2.11 on 2026-02-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_main_preview_url_productfile_storage_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_preview_url',
        ),
        migrations.AddField(
            model_name='product',
            name='main_preview_storage_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь превью в Supabase'),
        ),
    ]
