# Generated by Django 5.2.11 on 2026-03-09 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_main_preview_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('category', models.CharField(choices=[('wood', 'Wood'), ('glass', 'Glass'), ('metal', 'Metal'), ('plastic', 'Plastic'), ('stone', 'Stone'), ('fabric', 'Fabric'), ('leather', 'Leather'), ('ceramic', 'Ceramic'), ('sci_fi', 'Sci-Fi'), ('other', 'Other')], max_length=30, verbose_name='Категория')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('preview_image_storage_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь превью пресета')),
                ('base_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Базовый цвет')),
                ('roughness', models.FloatField(default=0.5, verbose_name='Roughness')),
                ('metalness', models.FloatField(default=0.0, verbose_name='Metalness')),
                ('transmission', models.FloatField(default=0.0, verbose_name='Transmission')),
                ('opacity', models.FloatField(default=1.0, verbose_name='Opacity')),
                ('emissive_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emissive color')),
                ('basecolor_texture_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Base color texture')),
                ('normal_texture_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Normal texture')),
                ('roughness_texture_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Roughness texture')),
                ('metallic_texture_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Metallic texture')),
                ('opacity_texture_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Opacity texture')),
                ('emissive_texture_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Emissive texture')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Пресет материала',
                'verbose_name_plural': 'Пресеты материалов',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productfile',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Файл товара', 'verbose_name_plural': 'Файлы товара'},
        ),
        migrations.AddField(
            model_name='product',
            name='animation_clips_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество клипов анимации'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_animation',
            field=models.BooleanField(default=False, verbose_name='Есть анимация'),
        ),
        migrations.AddField(
            model_name='product',
            name='viewer_error',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка подготовки viewer'),
        ),
        migrations.AddField(
            model_name='product',
            name='viewer_format',
            field=models.CharField(choices=[('glb', 'GLB'), ('gltf', 'GLTF'), ('obj', 'OBJ'), ('fbx', 'FBX'), ('blend', 'BLEND'), ('other', 'Other')], default='glb', max_length=20, verbose_name='Формат viewer'),
        ),
        migrations.AddField(
            model_name='product',
            name='viewer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Статус viewer-модели'),
        ),
        migrations.AddField(
            model_name='productfile',
            name='generated_from_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Промпт генерации'),
        ),
        migrations.AddField(
            model_name='productfile',
            name='preset_slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Slug пресета'),
        ),
        migrations.AddField(
            model_name='productfile',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_format',
            field=models.CharField(choices=[('glb', 'GLB'), ('gltf', 'GLTF'), ('obj', 'OBJ'), ('fbx', 'FBX'), ('blend', 'BLEND'), ('other', 'Other')], default='fbx', max_length=20, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file_type',
            field=models.CharField(choices=[('model_source', 'Source 3D Model'), ('viewer_model', 'Viewer 3D Model'), ('preview', 'Preview'), ('uv_preview', 'UV Preview'), ('wireframe_preview', 'Wireframe Preview'), ('texture_basecolor', 'Base Color Texture'), ('texture_normal', 'Normal Texture'), ('texture_roughness', 'Roughness Texture'), ('texture_metallic', 'Metallic Texture'), ('texture_opacity', 'Opacity Texture'), ('texture_emissive', 'Emissive Texture'), ('generated_texture', 'Generated Texture'), ('download_bundle', 'Download Bundle'), ('model', 'Legacy 3D Model'), ('texture', 'Legacy Texture'), ('other', 'Other')], default='model_source', max_length=30, verbose_name='Тип файла'),
        ),
        migrations.CreateModel(
            name='GeneratedTexture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='Промпт')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Статус')),
                ('image_storage_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь итоговой текстуры')),
                ('preview_storage_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь превью текстуры')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Высота')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_textures', to='products.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_textures', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_textures', to='products.materialpreset', verbose_name='Пресет')),
            ],
            options={
                'verbose_name': 'Сгенерированная текстура',
                'verbose_name_plural': 'Сгенерированные текстуры',
                'ordering': ['-created_at'],
            },
        ),
    ]
