# Generated by Django 5.2.11 on 2026-04-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='search_title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
