# Generated by Django 5.2.11 on 2026-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_search_description_product_search_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ администратора'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа'),
        ),
    ]
