# Generated by Django 5.2.11 on 2026-04-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_contactrequest_admin_reply_contactrequest_replied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Комиссия платформы, %'),
        ),
        migrations.AddField(
            model_name='order',
            name='external_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешний ID платежа'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_card', 'Bank Card'), ('sbp', 'SBP'), ('sberpay', 'SberPay')], default='bank_card', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(choices=[('mock', 'Mock'), ('yookassa', 'YooKassa')], default='mock', max_length=20, verbose_name='Провайдер оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма комиссии платформы'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма продавцу'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Комиссия платформы, %'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Комиссия платформы'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма продавцу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
