from django.urls import path

from .views import (
    AdminAllUsersView,
    AdminSellerRequestsView,
    ApproveSellerView,
    DeleteSellerBannerView,
    DeleteSellerAvatarView,
    DeleteSellerProfileView,
    DeleteUserAvatarView,
    LoginView,
    MarkNotificationReadView,
    MySellerProfileView,
    MyNotificationsView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ProfileView,
    PublicSellerProfileView,
    RegisterView,
    RejectSellerView,
    SellerProductsView,
    UploadSellerBannerView,
    UploadSellerAvatarView,
    UploadUserAvatarView,
    ChangePasswordView,
    UserPreferenceView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('me/', ProfileView.as_view(), name='profile'),
    path('me/preferences/', UserPreferenceView.as_view(), name='user-preferences'),
    path('me/notifications/', MyNotificationsView.as_view(), name='my-notifications'),
    path('me/notifications/<int:pk>/read/', MarkNotificationReadView.as_view(), name='mark-notification-read'),
    path('me/upload-avatar/', UploadUserAvatarView.as_view(), name='upload-user-avatar'),
    path('me/delete-avatar/', DeleteUserAvatarView.as_view(), name='delete-user-avatar'),

    path('seller/me/', MySellerProfileView.as_view(), name='my-seller-profile'),
    path('seller/me/upload-avatar/', UploadSellerAvatarView.as_view(), name='upload-seller-avatar'),
    path('seller/me/delete-avatar/', DeleteSellerAvatarView.as_view(), name='delete-seller-avatar'),
    path('seller/me/upload-banner/', UploadSellerBannerView.as_view(), name='upload-seller-banner'),
    path('seller/me/delete-banner/', DeleteSellerBannerView.as_view(), name='delete-seller-banner'),
    path('seller/me/delete-profile/', DeleteSellerProfileView.as_view(), name='delete-seller-profile'),
    path('seller/<int:pk>/', PublicSellerProfileView.as_view(), name='public-seller-profile'),
    path('seller/<int:pk>/products/', SellerProductsView.as_view(), name='seller-products'),

    path('admin/all/', AdminAllUsersView.as_view(), name='admin-all-users'),
    path('admin/seller-requests/', AdminSellerRequestsView.as_view(), name='admin-seller-requests'),
    path('<int:pk>/approve-seller/', ApproveSellerView.as_view(), name='approve-seller'),
    path('<int:pk>/reject-seller/', RejectSellerView.as_view(), name='reject-seller'),
    path("me/change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("password-reset/", PasswordResetRequestView.as_view(), name="password-reset"),
    path("password-reset/confirm/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
]
