# Generated by Django 5.2.11 on 2026-02-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=20, verbose_name='Статус продавца'),
        ),
    ]
