# Generated by Django 5.2.11 on 2026-02-26 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_seller_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, unique=True, verbose_name='Название магазина')),
                ('store_description', models.TextField(blank=True, null=True, verbose_name='Описание магазина')),
                ('store_avatar', models.ImageField(blank=True, null=True, upload_to='stores/avatars/', verbose_name='Аватар магазина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Профиль продавца',
                'verbose_name_plural': 'Профили продавцов',
                'ordering': ['store_name'],
            },
        ),
    ]
