# Generated by Django 5.2.11 on 2026-02-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='store_avatar_storage_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь аватара магазина в Supabase'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_storage_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь аватара в Supabase'),
        ),
    ]
