# Generated by Django 5.2.11 on 2026-04-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sellerprofile_store_avatar_storage_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_avatar_storage_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь аватара магазина в Object Storage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_storage_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь аватара в Object Storage'),
        ),
    ]
