# Generated by Django 5.2.11 on 2026-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='stores/banners/', verbose_name='Баннер магазина'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='store_banner_storage_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь баннера магазина в Object Storage'),
        ),
    ]
